<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\FrontendController;
use Illuminate\Support\Facades\Route;

// Frontend Routes
Route::get('/', [FrontendController::class, 'home'])->name('home');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/trucks', [FrontendController::class, 'trucks'])->name('trucks');
Route::get('/booking', [FrontendController::class, 'booking'])->name('booking');

// Backend Dashboard & Auth routes generated by Laravel Breeze
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    
    // BACKEND TEAM: Tambahkan route untuk manajemen CRUD truk di sini
    // Route::resource('admin/trucks', AdminTruckController::class);
});

require __DIR__.'/auth.php';
